Support Vector Machines - is a model that can do both classification and 
regression. 

<img src="svm1.png" width=300, height=200>

References: https://commons.wikimedia.org/wiki/File:SVM_Example_of_Hyperplanes.png

Let's look at another example

<img src="svm2.png" width=300, height=200>

https://commons.wikimedia.org/wiki/File:SVM_margin.png

Support vectors are the points that lie close to the decision boundary. 

The dataset will comprise of $(x_i, y_i)$ where $y_i$ is either 1 or -1 
that indicates the class that $x_i$ belongs.

Our goal is to find a hyperplane that separates the two classes with maximum margin. This hyperplane can be represented by 
$\vec{w}\vec{x} - \vec{b} = 0.$

Using the training dataset, we compute $\vec{w}$ and $\vec{b}.$ 

Any point that lies on or above 

$\vec{w}\vec{x} - \vec{b} = 1$ will be classified as class 1 
and any point thay lies on or below

$\vec{w}\vec{x} - \vec{b} = -1$ will be classified as 
class 2.

The distance between the two hyperplanes is $\frac{2}{||\vec{w}||},$ we want to maximize this which is same as minimizing $||\vec{w}||.$ 

In Hard-margin, we are very particular about the margin. No data points can lie within the margin. So hard-margins are narrow.

In Soft-margin, data points can lie within the margin. Soft-margins are wide. 

The loss function for SVM is defined by

$max(0, 1-y_i(\vec{w}.\vec{x_i} - b))$ 


y_i is the true value

y_hat is the predicted value

if true value and predicted value are same then 

y_i is 1, yhat is 1

1 - y_true *y_hat = 1-1 = 0

max(0, 0) = 0

y_i is -1, yhat is -1

1 - y_true *y_hat = 1-(-1)(-1) = 0


y_i is -1, yhat is 1

1 - y_true *y_hat = 1-(-1)(1) = 2

max(0,2) = 2

y_i is 1, yhat is-1

1 - y_true *y_hat = 1-(1)(-1) = 2

max(0,2) = 2

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# https://archive.ics.uci.edu/ml/datasets/banknote+authentication

df = pd.read_csv("bill_authentication.csv")
df1 = df.copy(deep=True)

In [3]:
df.shape

(1372, 5)

In [4]:
df.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [5]:
df["Class"].unique()

array([0, 1], dtype=int64)

In [6]:
df["Class"].value_counts()

Class
0    762
1    610
Name: count, dtype: int64

Important Links to understand skewness, curtosis (kurtosis), entropy

https://www.mathsisfun.com/data/skewness.html

https://www.statology.org/can-kurtosis-be-negative/
    
https://towardsdatascience.com/entropy-is-a-measure-of-uncertainty-e2c000301c2c

In [7]:
xc = df.drop('Class', axis=1)
yc = df['Class']

In [9]:
from sklearn.model_selection import train_test_split
xc_train, xc_test, yc_train, yc_test = train_test_split(xc, yc, test_size = 0.20)

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(xc_train) # mean and standard deviation for x-train

train_sv = scaler.transform(xc_train) 

test_sv = scaler.transform(xc_test)

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.svm import SVC

from sklearn import metrics

In [12]:
svclassifier = SVC(kernel='linear') # creating an object
svclassifier.fit(train_sv, yc_train) # fiting the data to the model

yc_pred = svclassifier.predict(test_sv)

print(confusion_matrix(yc_test,yc_pred))
print(classification_report(yc_test,yc_pred))

# Model Accuracy, how often is the classifier correct?
print("Accuracy:", metrics.accuracy_score(yc_test, yc_pred))

[[149   1]
 [  1 124]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       150
           1       0.99      0.99      0.99       125

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275

Accuracy: 0.9927272727272727


In [13]:
# building a SVC with kernel = "rbf"

svc2 = SVC() # creating an object
svc2.fit(train_sv, yc_train) # fiting the data to the model

yc_pred = svc2.predict(test_sv)

print(confusion_matrix(yc_test,yc_pred))
print(classification_report(yc_test,yc_pred))


# Model Accuracy, how often is the classifier correct?
print("Accuracy:", metrics.accuracy_score(yc_test, yc_pred))

[[150   0]
 [  0 125]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       150
           1       1.00      1.00      1.00       125

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275

Accuracy: 1.0


In [14]:
# building a SVC with kernel = "polynomial" with degree 3


svc3 = SVC(kernel="poly", degree=3) # creating an object
svc3.fit(train_sv, yc_train) # fiting the data to the model

yc_pred = svc3.predict(test_sv)

print(confusion_matrix(yc_test,yc_pred))
print(classification_report(yc_test,yc_pred))

# Model Accuracy, how often is the classifier correct?
print("Accuracy:", metrics.accuracy_score(yc_test, yc_pred))

[[149   1]
 [  0 125]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       150
           1       0.99      1.00      1.00       125

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275

Accuracy: 0.9963636363636363


### Kernel Trick


References: http://www.eric-kim.net/eric-kim-net/posts/1/kernel_trick.html

https://prateekvjoshi.com/2012/09/01/kernel-functions-for-machine-learning/

<img src="kernel1.png" width=500 height=400>

#### Different kernel functions

References: https://www.slideshare.net/okamoto-laboratory/families-of-triangular-norm-based-kernel-function-and-its-application-to-kernel-kmeans-conference

<img src="kernel2.png" width=400, height=300>

When to use which kernel?

Use linear SVM for linear problems and non-linear kernels such as RBF for non-linear data. 

Let us consider SVM with kernel trick

In [15]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=colnames)

print(irisdata.columns)

Index(['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class'], dtype='object')


In [16]:
print(irisdata.shape)

(150, 5)


In [17]:
print(irisdata.head())

   sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [18]:
print(irisdata['Class'].unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [19]:
irisdata1 = irisdata.copy(deep=True)

In [20]:
c = {'Iris-setosa':0, 'Iris-versicolor':1, 'Iris-virginica':2}

#irisdata1.Class = irisdata1.Class.apply(lambda x: c[x])
#irisdata["Class"] = isirsdata["Class"].map(c)

irisdata.Class = [c[item] for item in irisdata.Class] # list comprehension 

In [21]:
print(irisdata.Class[0:2])
print(irisdata.head())

0    0
1    0
Name: Class, dtype: int64
   sepal-length  sepal-width  petal-length  petal-width  Class
0           5.1          3.5           1.4          0.2      0
1           4.9          3.0           1.4          0.2      0
2           4.7          3.2           1.3          0.2      0
3           4.6          3.1           1.5          0.2      0
4           5.0          3.6           1.4          0.2      0


In [22]:
x = irisdata.drop('Class', axis=1)
y = irisdata['Class']

In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state=42)

In [24]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(x_train) # mean and standard deviation for x-train

x_train = scaler.transform(x_train) 

x_test = scaler.transform(x_test)

Links to understand $gamma,$ and degree

https://scikit-learn.org/stable/modules/svm.html

In [25]:
# polynomial kernel

from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=2)
svclassifier.fit(x_train, y_train)

SVC(degree=2, kernel='poly')

In [26]:
y_pred = svclassifier.predict(x_test)

In [27]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Model Accuracy, how often is the classifier correct?
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

[[9 0 1]
 [0 9 0]
 [5 1 5]]
              precision    recall  f1-score   support

           0       0.64      0.90      0.75        10
           1       0.90      1.00      0.95         9
           2       0.83      0.45      0.59        11

    accuracy                           0.77        30
   macro avg       0.79      0.78      0.76        30
weighted avg       0.79      0.77      0.75        30

Accuracy: 0.7666666666666667


In [28]:
# RBF kernel

from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf') 
svclassifier.fit(x_train, y_train)

SVC()

In [29]:
y_pred = svclassifier.predict(x_test)

In [30]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy: 1.0


#### Hyperparameters tuning

svc

kernel

c

Gridsearch considers all the combinations that are specified in kernel and c
it will find the best kernel and c that give optimal accuracy

In [32]:
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

from sklearn.model_selection import GridSearchCV

parameters = {'kernel':['linear', 'rbf', 'poly'], 'C':[1, 5, 10]}

svc = SVC()

clf = GridSearchCV(svc, param_grid = parameters, cv = 3, verbose=True, n_jobs=-1)

final_clf = clf.fit(x_train, y_train)

print(sorted(final_clf.cv_results_.keys()))

Fitting 3 folds for each of 9 candidates, totalling 27 fits
['mean_fit_time', 'mean_score_time', 'mean_test_score', 'param_C', 'param_kernel', 'params', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score', 'std_fit_time', 'std_score_time', 'std_test_score']


In [33]:
print(final_clf.best_estimator_)
print(final_clf.best_params_)

SVC(C=1, kernel='linear')
{'C': 1, 'kernel': 'linear'}


In [34]:
# Using the best parameters from the above GridSearchCV
# we build another svc model

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.svm import SVC

svc = SVC(kernel = 'rbf', C=5)
svc.fit(train_sv, yc_train) # fiting the data to the model

yc_pred = svc.predict(test_sv)
print(confusion_matrix(yc_test,yc_pred))
print(classification_report(yc_test,yc_pred))

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

[[150   0]
 [  0 125]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       150
           1       1.00      1.00      1.00       125

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275

Accuracy: 1.0


In [35]:
"""
In-class activity: consider Titanic dataset and apply SVM along with 
GridSearchCV to determine the best parameteres for kernel and C. 

You can use the titanic dataframe that we saved last class. 
"""

'\nIn-class activity: consider Titanic dataset and apply SVM along with \nGridSearchCV to determine the best parameteres for kernel and C. \n\nYou can use the titanic dataframe that we saved last class. \n'